/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RShortCodeRouteImport } from './routes/r.$shortCode'
import { Route as QrCreateRouteImport } from './routes/qr/create'
import { Route as QrIdRouteImport } from './routes/qr.$id'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as ApiQrListRouteImport } from './routes/api.qr.list'
import { Route as ApiQrCreateRouteImport } from './routes/api.qr.create'
import { Route as ApiQrIdRouteImport } from './routes/api.qr.$id'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api.auth.reset-password'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiQrIdDownloadRouteImport } from './routes/api.qr.$id.download'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RShortCodeRoute = RShortCodeRouteImport.update({
  id: '/r/$shortCode',
  path: '/r/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCreateRoute = QrCreateRouteImport.update({
  id: '/qr/create',
  path: '/qr/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIdRoute = QrIdRouteImport.update({
  id: '/qr/$id',
  path: '/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrListRoute = ApiQrListRouteImport.update({
  id: '/api/qr/list',
  path: '/api/qr/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrCreateRoute = ApiQrCreateRouteImport.update({
  id: '/api/qr/create',
  path: '/api/qr/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrIdRoute = ApiQrIdRouteImport.update({
  id: '/api/qr/$id',
  path: '/api/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrIdDownloadRoute = ApiQrIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiQrIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/qr/$id': typeof QrIdRoute
  '/qr/create': typeof QrCreateRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/qr/$id': typeof ApiQrIdRouteWithChildren
  '/api/qr/create': typeof ApiQrCreateRoute
  '/api/qr/list': typeof ApiQrListRoute
  '/api/qr/$id/download': typeof ApiQrIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/qr/$id': typeof QrIdRoute
  '/qr/create': typeof QrCreateRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/qr/$id': typeof ApiQrIdRouteWithChildren
  '/api/qr/create': typeof ApiQrCreateRoute
  '/api/qr/list': typeof ApiQrListRoute
  '/api/qr/$id/download': typeof ApiQrIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/qr/$id': typeof QrIdRoute
  '/qr/create': typeof QrCreateRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/qr/$id': typeof ApiQrIdRouteWithChildren
  '/api/qr/create': typeof ApiQrCreateRoute
  '/api/qr/list': typeof ApiQrListRoute
  '/api/qr/$id/download': typeof ApiQrIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/demo-names'
    | '/qr/$id'
    | '/qr/create'
    | '/r/$shortCode'
    | '/sitemap/xml'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/qr/$id'
    | '/api/qr/create'
    | '/api/qr/list'
    | '/api/qr/$id/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/demo-names'
    | '/qr/$id'
    | '/qr/create'
    | '/r/$shortCode'
    | '/sitemap/xml'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/qr/$id'
    | '/api/qr/create'
    | '/api/qr/list'
    | '/api/qr/$id/download'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/demo-names'
    | '/qr/$id'
    | '/qr/create'
    | '/r/$shortCode'
    | '/sitemap/xml'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/qr/$id'
    | '/api/qr/create'
    | '/api/qr/list'
    | '/api/qr/$id/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  QrIdRoute: typeof QrIdRoute
  QrCreateRoute: typeof QrCreateRoute
  RShortCodeRoute: typeof RShortCodeRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiQrIdRoute: typeof ApiQrIdRouteWithChildren
  ApiQrCreateRoute: typeof ApiQrCreateRoute
  ApiQrListRoute: typeof ApiQrListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shortCode': {
      id: '/r/$shortCode'
      path: '/r/$shortCode'
      fullPath: '/r/$shortCode'
      preLoaderRoute: typeof RShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/create': {
      id: '/qr/create'
      path: '/qr/create'
      fullPath: '/qr/create'
      preLoaderRoute: typeof QrCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$id': {
      id: '/qr/$id'
      path: '/qr/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof QrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/list': {
      id: '/api/qr/list'
      path: '/api/qr/list'
      fullPath: '/api/qr/list'
      preLoaderRoute: typeof ApiQrListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/create': {
      id: '/api/qr/create'
      path: '/api/qr/create'
      fullPath: '/api/qr/create'
      preLoaderRoute: typeof ApiQrCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/$id': {
      id: '/api/qr/$id'
      path: '/api/qr/$id'
      fullPath: '/api/qr/$id'
      preLoaderRoute: typeof ApiQrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/$id/download': {
      id: '/api/qr/$id/download'
      path: '/download'
      fullPath: '/api/qr/$id/download'
      preLoaderRoute: typeof ApiQrIdDownloadRouteImport
      parentRoute: typeof ApiQrIdRoute
    }
  }
}

interface ApiQrIdRouteChildren {
  ApiQrIdDownloadRoute: typeof ApiQrIdDownloadRoute
}

const ApiQrIdRouteChildren: ApiQrIdRouteChildren = {
  ApiQrIdDownloadRoute: ApiQrIdDownloadRoute,
}

const ApiQrIdRouteWithChildren =
  ApiQrIdRoute._addFileChildren(ApiQrIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  QrIdRoute: QrIdRoute,
  QrCreateRoute: QrCreateRoute,
  RShortCodeRoute: RShortCodeRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiQrIdRoute: ApiQrIdRouteWithChildren,
  ApiQrCreateRoute: ApiQrCreateRoute,
  ApiQrListRoute: ApiQrListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
